name: Flight Monitor

on:
  workflow_dispatch:

jobs:
  check-flights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Fetch EL AL flights JSON
        run: curl -s https://www.elal.com/api/SeatAvailability/lang/heb/flights -o flights.json

      - name: Run flight monitor
        run: node checkFlights.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
